Mo3aqin/Models/EmployeeDecision.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Mo3aqin.Models
{
    public class EmployeeDecision
    {
        [Key]
        public int DecId { get; set; }
        public DateTime DecDate { get; set; }
        public string DecFile { get; set; }
        public string Notes { get; set; }
        [ForeignKey("Employee")]
        public int? EmpId { get; set; }
        public Employee Employee { get; set; }
    }
}

Mo3aqin/Controllers/EmpolyeeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mo3aqin.Constane;
using Mo3aqin.Data;
using Mo3aqin.Helpers;
using Mo3aqin.Models;
using Mo3aqin.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Mo3aqin.Controllers
{
    public class EmpolyeeController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IMapper mapper;

        public EmpolyeeController(ApplicationDbContext _db, IMapper _mapper)
        {
            db = _db;
            this.mapper = _mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult EmpolyeeForm()
        {
          
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EmpolyeeForm(Employee_VM emp)
        {

            #region//d.EmpName = emp.EmpName;
            //d.JopName = emp.JopName;
            //d.PassportExpDate = emp.PassportExpDate;
            //d.MaritalStatus = emp.MaritalStatus;
            //d.TimeType = emp.TimeType;
            //d.CivilianNumber = emp.CivilianNumber;
            //d.Address = emp.Address;
            //d.PhoneNumber = emp.PhoneNumber;
            //d.HomeNumber = emp.HomeNumber;
            //d.Notes = emp.Notes;
            #endregion

            try
            {
                if (ModelState.IsValid)
                {

                    var data = mapper.Map<Employee>(emp);


                    data.EmpImage = await Help.SaveFileAsync(emp.EmpImage, FilePath.EmpPath);
                    data.CivilianEmp = await Help.SaveFileAsync(emp.CivilianEmp, FilePath.EmpPath);
                    data.PassportImage = await Help.SaveFileAsync(emp.PassportImage, FilePath.EmpPath);

                    db.Employees.Add(data);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(emp); 
            }catch(Exception ex)
            {
                EventLog log = new EventLog();
                log.Source = "Admin Dashboard";
                log.WriteEntry(ex.Message, EventLogEntryType.Error);
                return View(emp);
            }
        }
        public async Task<IActionResult> LoadAllEmps(int pageNumber = 1, int pageSize = 10)
        {
            var coach = await db.Employees.Select(x => new Employee_VM
            {
               EmpId=x.EmpId,
               EmpName=x.EmpName,
               EmpImageString=x.EmpImage
            }).ToListAsync();
            var pagedData = Pagination.PagedResult(coach, pageNumber, pageSize);
            return Json(pagedData);
        }
        public async Task<IActionResult> DeletEmp(int id)
        {
            try
            {
                var Emp = await db.Employees.Where(x => x.EmpId == id).FirstOrDefaultAsync();
                if (Emp == null)
                {
                    return Json(false);
                }
                else
                {
                    db.Employees.Remove(Emp);
                    var res = await db.SaveChangesAsync();
                    if (res > 0)
                    {
                        return Json(true);
                    }
                    else
                    {
                        return Json(false);
                    }

                }
            }
            catch (Exception ex)
            {

                return Json(false);
            }


        }
        public async Task<IActionResult> ViewEmpolyee(int empId)
        {
            ViewBag.empId = empId;
            return View();
        }
        public async Task<IActionResult> GetEmpById(int empId)
        {
            var coach = await db.Employees.Where(x => x.EmpId == empId).Select(x => new Employee_VM
            {
                EmpId = x.EmpId,
                JopName=x.JopName,
                Address = x.Address,
                Birthdate = x.Birthdate,
                CivilianEmpString = x.CivilianEmp,
                CivilianNumber = x.CivilianNumber,
                EmpImageString = x.EmpImage,
                EmpName = x.EmpName,
                HomeNumber = x.HomeNumber,
                MaritalStatus = x.MaritalStatus,
                NationalityId = x.NationalityId,
                Notes = x.Notes,
                PassportExpDate = x.PassportExpDate,
                PassportImageString = x.PassportImage,
                PassportNumber = x.PassportNumber,
                PhoneNumber = x.PhoneNumber,
                TimeType = x.TimeType,
                Active = x.Active == true ?(byte)1 :(byte)0
            }).FirstOrDefaultAsync();
            return Json(coach);
        }
        public async Task<IActionResult> EditEmployee(int empId)
        {
            ViewBag.empId = empId;
            return View();
        }
        public async Task<IActionResult> EditEmpById(Employee_VM emp)
        {
            try
            {
                var Emp = await db.Employees.Where(x => x.EmpId == emp.EmpId).FirstOrDefaultAsync();
                if (Emp == null)
                {
                    return Json(false);
                }
                else
                {
                    Emp.Address = emp.Address;
                    Emp.Birthdate = emp.Birthdate;
                    Emp.CivilianEmp = emp.CivilianEmp == null ? Emp.CivilianEmp : await Help.SaveFileAsync(emp.CivilianEmp, FilePath.CoachPath);
                    Emp.CivilianNumber = emp.CivilianNumber;
                    Emp.EmpImage = emp.EmpImage == null ? Emp.EmpImage : await Help.SaveFileAsync(emp.EmpImage, FilePath.CoachPath);
                    Emp.EmpName = emp.EmpName;
                    Emp.HomeNumber = emp.HomeNumber;
                    Emp.MaritalStatus = emp.MaritalStatus;
                    Emp.NationalityId = emp.NationalityId;
                    Emp.Notes = emp.Notes;
                    Emp.PassportExpDate = emp.PassportExpDate;
                    Emp.PassportImage = emp.PassportImage == null ? Emp.PassportImage : await Help.SaveFileAsync(emp.PassportImage, FilePath.CoachPath);
                    Emp.PassportNumber = emp.PassportNumber;
                    Emp.PhoneNumber = emp.PhoneNumber;
                    Emp.TimeType = emp.TimeType;
                    var res = await db.SaveChangesAsync();
                    if (res > 0)
                    {
                        return Json(true);
                    }
                    else
                    {
                        return Json(false);
                    }

                }
            }
            catch (Exception ex)
            {

                return Json(false);
            }


        }
        public IActionResult EmployeeDecision()
        {
            return View();
        }
        public async Task<IActionResult> AddEmpDec(Decision_VM decision)
        {
            try
            {
                var Dec = new EmployeeDecision() { EmpId = decision.Id, DecDate = decision.DecDate, Notes = decision.Notes };
                Dec.DecFile = decision.DecFile == null ? null : await Help.SaveFileAsync(decision.DecFile, FilePath.EmpPath);
                await db.EmployeeDecisions.AddAsync(Dec);
                int res = await db.SaveChangesAsync();
                if (res > 0)
                {
                    return Json(true);
                }
                else
                {
                    return Json(false);
                }
            }
            catch (Exception ex)
            {

                return Json(false);
            }

        }
        public async Task<IActionResult> GetEmpDec(int pageNumber = 1, int pageSize = 10)
        {
            try
            {
                var Dec = await db.EmployeeDecisions.Select(x => new Decision_VM { Name = x.Employee.EmpName, DecDate = x.DecDate, Notes = x.Notes, DecId = x.DecId }).ToListAsync();

                var pagedData = Pagination.PagedResult(Dec, pageNumber, pageSize);
                return Json(pagedData);
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        public async Task<IActionResult> GetDecById(int DecId)
        {
            try
            {
                return Json(await db.EmployeeDecisions.Where(x => x.DecId == DecId).Select(x => new Decision_VM { Name = x.Employee.EmpName, DecDate = x.DecDate, Notes = x.Notes, DecId = x.DecId, Id = x.EmpId }).FirstOrDefaultAsync());
            }
            catch (Exception ex)
            {

                throw;
            }

        }
        public async Task<IActionResult> EditEmpDec(Decision_VM decision)
        {
            try
            {
                var dec = await db.EmployeeDecisions.Where(x => x.DecId == decision.DecId).FirstOrDefaultAsync();
                dec.EmpId = decision.Id;
                dec.DecDate = decision.DecDate;
                dec.Notes = decision.Notes;
                dec.DecFile = decision.DecFile == null ? null : await Help.SaveFileAsync(decision.DecFile, FilePath.EmpPath);
                int res = await db.SaveChangesAsync();
                if (res > 0)
                {
                    return Json(true);
                }
                else
                {
                    return Json(false);
                }
            }
            catch (Exception ex)
            {

                return Json(false);
            }
        }
        public async Task<IActionResult> DeletDec(int id)
        {
            try
            {
                var dec = await db.EmployeeDecisions.Where(x => x.DecId == id).FirstOrDefaultAsync();
                db.EmployeeDecisions.Remove(dec);
                int res = await db.SaveChangesAsync();
                if (res > 0)
                {

Mo3aqin/Views/Empolyee/EmpolyeeForm.cshtml
@model Employee_VM
@{ ViewBag.Titel = "تسجيل موظف";}
<form class="Form" asp-action="EmpolyeeForm" asp-controller="Empolyee" enctype="multipart/form-data" method="post">
    <div class="mx-auto text-center my-4">
        <h2 class="my-3">تسجيل موظف جديد </h2>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="text-one">اسم الموظف</label>
            <input asp-for="EmpName" type="text" id="text-one" class="form-control">
            <span class="text-danger" asp-validation-for="EmpName"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="text-two">المسمى الوظيفي</label>
            <input asp-for="JopName" type="text" id="text-two" class="form-control">
            <span class="text-danger" asp-validation-for="JopName"></span>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="file-one">صورة الموظف</label>
            <div class="d-flex align-items-center ">
                <input asp-for="EmpImage" type="file" id="imageUpload1" class="form-control-file w-auto">
                <img class="rounded-circle m-2" id="imageUpload1img" style="display:none" src="" alt="img" width="150" height="150" />
            </div>
            <span class="text-danger" asp-validation-for="EmpImage"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="file-two">مدنية الموظف</label>
            <div class="d-flex align-items-center ">
                <input asp-for="CivilianEmp" type="file" id="imageUpload2" class="form-control-file w-auto">

                <img class="rounded-circle m-2" id="imageUpload2img" style="display:none" src="" alt="img" width="150" height="150" />
                </div>
                <span class="text-danger" asp-validation-for="CivilianEmp"></span>
            </div>
        </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="file-three">صورة الجواز</label>
            <div class="d-flex align-items-center ">
                <input asp-for="PassportImage" type="file" id="imageUpload3" class="form-control-file w-auto">
                <img class="rounded-circle m-2" id="imageUpload3img" style="display:none" src="" alt="img" width="150" height="150" />
                </div>
                <span class="text-danger" asp-validation-for="PassportImage"></span>

            </div>
            <div class="form-group col-md-6">
                <label for="date-input-one">تاريخ الميلاد </label>
                <div class="input-group">
                    <input asp-for="Birthdate" type="text" class="form-control drgpicker" id="date-input-one" value="" aria-describedby="button-addon2">
                    <br />
                    <span class="text-danger" asp-validation-for="Birthdate"></span>

                    <div class="input-group-append">
                        <div class="input-group-text" id="button-addon-date">
                            <span class="fe fe-calendar fe-16"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label for="date-input-one">تاريخ انتهاء الجواز</label>
                <div class="input-group">
                    <input asp-for="PassportExpDate" type="text" class="form-control drgpicker" id="date-input-one" value="" aria-describedby="button-addon2">
                    <br />
                    <span class="text-danger" asp-validation-for="PassportExpDate"></span>

                    <div class="input-group-append">
                        <div class="input-group-text" id="button-addon-date">
                            <span class="fe fe-calendar fe-16"></span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="text-three">رقم الجواز</label>
            <input asp-for="PassportNumber" type="text" id="text-three" class="form-control">
            <span class="text-danger" asp-validation-for="PassportNumber"></span>

        </div>
        <div class="form-group col-md-6">
            <label for="select-one">الجنسية</label>
            <select asp-for="NationalityId" class="form-control " id="nationality">
            </select>
            <span class="text-danger" asp-validation-for="NationalityId"></span>

        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="text-four">الرقم المدنى</label>
            <input asp-for="CivilianNumber" type="text" id="text-four" class="form-control">
            <span class="text-danger" asp-validation-for="CivilianNumber"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="text-five">عنوان السكن</label>
            <input asp-for="Address" type="text" id="text-five" class="form-control">
            <span class="text-danger" asp-validation-for="Address"> </span>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="check-one">الحالة الإجتماعية</label>
            <div class="d-flex flex-wrap align-items-center" id="check-one">
                <div class="custom-control custom-radio">
                    <input asp-for="MaritalStatus" value="متزوج" type="radio" id="one" name="MaritalStatus" class="custom-control-input">
                    <label class="custom-control-label" for="one">متزوج</label>
                </div>
                <div class="custom-control custom-radio">
                    <input asp-for="MaritalStatus" type="radio" id="two" value="أعزب" name="MaritalStatus" class="custom-control-input" checked>
                    <label class="custom-control-label" for="two">أعزب</label>
                </div>
            </div>
        </div>
        <div class="form-group col-md-6">
            <label for="check-two">نوع الدوام</label>
            <div class="d-flex flex-wrap align-items-center" id="check-two">
                <div class="custom-control custom-radio">
                    <input asp-for="TimeType" value="نصف دوام" type="radio" id="three" name="TimeType" class="custom-control-input">
                    <label class="custom-control-label" for="three">نصف دوام</label>
                </div>
                <div class="custom-control custom-radio">
                    <input asp-for="TimeType" value="دوام كامل" type="radio" id="four" name="TimeType" class="custom-control-input" checked>
                    <label class="custom-control-label" for="four">دوام كامل</label>
                </div>
            </div>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <p class="col-12 font-weight-bold">الهواتف</p>
        <div class="form-group col-md-6">
            <label for="text-six">الموبايل</label>
            <input asp-for="PhoneNumber" type="text" id="text-six" class="form-control">
            <span class="text-danger" asp-validation-for="PhoneNumber"> </span>
        </div>
        <div class="form-group col-md-6">
            <label for="text-seven">المنزل</label>
            <input asp-for="HomeNumber" type="text" id="text-seven" class="form-control">

        </div>
    </div>
    <hr class="my-2">
    <div class="form-group">
        <div class="d-flex flex-wrap align-items-center">
            <label class="m-0 mr-3" for="name">حالة الموظف</label>
            <div class="custom-control custom-radio">
                <input asp-for="Active" type="radio" id="status_active" value="1" name="Active" class="custom-control-input" checked>
                <label class="custom-control-label" for="status_active">فعّال</label>
            </div>
            <div class="custom-control custom-radio">
                <input asp-for="Active" type="radio" id="status_not_active" value="0" name="Active" class="custom-control-input">
                <label class="custom-control-label" for="status_not_active">غير فعّال</label>
            </div>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-group">
        <label class="" for="text-nine">ملاحظات</label>
        <textarea asp-for="Notes" id="text-nine" name="Notes" class="form-control" id="" cols="30" rows="5"></textarea>
    </div>
    <hr class="my-2">
    <button class="btn btn-lg btn-primary btn-block" type="submit">حفظ</button>
    <p class="mt-5 mb-3 text-muted text-center">© 2021</p>
</form>

<script>
    $(document).ready(function () {

        LoadALLNationality();
    });
    function LoadALLNationality() {
        $.ajax({
            url: "/Coach/GetAllNationality",
            type: "GET",

            dataType: "json",
            success: function (result) {
                debugger;
                var html = '<option value="-1">اختر جنسية</option>';
                $.each(result, function (key, item) {

                    html += '<option value="' + item.nationalityId + '">' + item.nationalityName + '</option>';

                });

                $("#nationality").html(html)

            }


        });
    }
    document.getElementById('imageUpload1').onchange = function () {
        $('#imageUpload1img').show();
        var src = URL.createObjectURL(this.files[0])
        document.getElementById('imageUpload1img').src = src
    }
    document.getElementById('imageUpload2').onchange = function () {
        $('#imageUpload2img').show();
        var src = URL.createObjectURL(this.files[0])
        document.getElementById('imageUpload2img').src = src
    }
    document.getElementById('imageUpload3').onchange = function () {
        $('#imageUpload3img').show();
        var src = URL.createObjectURL(this.files[0])
        document.getElementById('imageUpload3img').src = src
    }
</script>

Mo3aqin/Views/Empolyee/Index.cshtml
@{ ViewBag.Titel = "الموظفين";}
<div class="input-group-append">
    <a asp-action="EmpolyeeForm" id="add" type="button" class="btn btn-primary">اضافة موظف جديدة</a>
</div>
<table class="table table-striped mt-4">
    <thead>
        <tr class="bg-primary text-white">
            <th>اسم الموظف</th>
            <th>صورة الموظف</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="Data">
    </tbody>
</table>
<!-- pagination -->
<nav aria-label="Page navigation example">
    <ul class="pagination">
    </ul>
</nav>
<script>

    $(document).ready(function () {

        LoadAllEmps(1);
    });

    function LoadAllEmps(pageNum) {
        $.ajax({
            url: "/Empolyee/LoadAllEmps?pageNumber=" + pageNum + "&pageSize=" + 10,
            type: "GET",
            dataType: "json",
            success: function (result) {
                $(".pagination").empty();
                var html = '';

                $.each(result.data, function (key, item) {
                    debugger;
                    $("#Data").append(SeedDataTabel(item));
                });
                PaggingTemplate(result.totalPages, result.currentPage);
            }
        });
    }
    function SeedDataTabel(data) {
        return ' <tr id="tr_' + data.empId + '"><td>' + data.empName + '</td><td><img width="100" height="100" src="/Images/Emp/' + data.empImageString + '" alt=""></td><td>' +
            '<a class="btn btn-success" href="javascript:void(0);"  onclick="ViewEmpolyee(' + data.empId + ')">تفاصيل</a>' +
            '<a class="btn btn-primary" href="javascript:void(0);"  onclick="EditEmployee(' + data.empId + ')">تعديل</a>' +
            '<a class="btn btn-danger" href="javascript:void(0);" onclick="DeletEmp(' + data.empId + ')">حذف</a></td> </tr>'
    }
    function PaggingTemplate(totalPage, currentPage) {

        var template = "";
        var TotalPages = totalPage;
        var CurrentPage = currentPage;
        var PageNumberArray = Array();


        var countIncr = 1;
        if (currentPage != 1) {

            for (var i = currentPage - 1; i <= totalPage; i++) {

                PageNumberArray[0] = currentPage - 1;
                if (PageNumberArray[countIncr - 1] != totalPage) {
                    PageNumberArray[countIncr] = i + 1;
                }
                countIncr++;
            };
        }
        else {
            for (var i = currentPage; i <= totalPage; i++) {

                PageNumberArray[0] = currentPage;
                if (totalPage != currentPage && PageNumberArray[countIncr - 1] != totalPage) {
                    PageNumberArray[countIncr] = i + 1;
                }
                countIncr++;
            };
        }
        PageNumberArray = PageNumberArray.slice(0, 5);
        var FirstPage = 1;
        var LastPage = totalPage;
        if (totalPage != currentPage) {
            var ForwardOne = currentPage + 1;
        }
        var BackwardOne = 1;
        if (currentPage > 1) {
            BackwardOne = currentPage - 1;
        }

        //template = "<p>" + CurrentPage + " of " + TotalPages + " pages</p>"
        template = template + '<li class="page-item">' +
            '<a onclick="LoadAllProudct(' + BackwardOne + ')" class="page-link"  aria-label="Previous">' +
            '<span aria-hidden="true">&laquo;</span>' +
            '<span class="sr-only">Previous</span>' +
            '</a>' +
            '</li>';


        var numberingLoop = "";
        for (var i = 0; i < PageNumberArray.length; i++) {
            if (PageNumberArray[i] == currentPage) {
                numberingLoop = numberingLoop + '<li  class="page-item active"><a onclick="LoadAllProudct(' + PageNumberArray[i] + ')"  class="page-link" href="#">' + PageNumberArray[i] + '</a></li>'
            }
            else {
                numberingLoop = numberingLoop + '<li class="page-item"><a onclick="LoadAllProudct(' + PageNumberArray[i] + ')"  class="page-link" href="#">' + PageNumberArray[i] + '</a></li>'
            }

        }
        template = template + numberingLoop + '<li class="page-item">' +
            ' <a  onclick="LoadAllProudct(' + ForwardOne + ')" class="page-link"  aria-label="Next">' +
            '<span aria-hidden="true">&raquo;</span>' +
            '<span class="sr-only">Next</span>' +
            '</a>' +
            '</li>';

        $(".pagination").append(template);


    }
    function EditEmployee(id) {
        debugger;
        window.location.href = "/Empolyee/EditEmployee?empId="+id;
    }
    function ViewEmpolyee(id) {

        window.location.href = "/Empolyee/ViewEmpolyee?empId=" + id;
    }
    function DeletEmp(id) {
        swal({
            title: 'هل انت متأكد؟',
            text: "اذا قمت بمسح هذا لن تستطيع استرجاعه ثانيتا!",
            icon: 'warning',
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        url: "/Empolyee/DeletEmp?id=" + id,
                        type: "POST",
                        dataType: 'json',
                        success: function (result) {

                            if (result == true) {
                                swal("تم الحذف بنجاح", {
                                    icon: "success",
                                });
                                $('#tr_' + id).remove();
                            }
                            else {
                                swal("حدث خطا او تم استخدام البيانات من قبل", "", "error");
                            }
                        }
                    });

                }
            });
    }
</script>