Mo3aqin/Models/Championship.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Mo3aqin.Models
{
    public class Championship
    {
        [Key]
        public int ChampId { get; set; }
        public string ChampName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Invitaion { get; set; }
        [ForeignKey("Country")]
        public int CountryId { get; set; }
        public string City { get; set; }
        public string Season { get; set; }
        public string ChampDuration { get; set; }
        public int EmpsNum { get; set; }
        public int PlayersNum { get; set; }
        public int CoachsNum { get; set; }
        public string Notes { get; set; }
        public Country Country { get; set; }
        public List<Game> Games { get; set; }
        public List<ChampionshipGames> ChampionshipGames { get; set; }
    }
}

Mo3aqin/Controllers/ChampionshipController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Mo3aqin.Constane;
using Mo3aqin.Data;
using Mo3aqin.Helpers;
using Mo3aqin.Models;
using Mo3aqin.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mo3aqin.Controllers
{
    public class ChampionshipController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IMapper mapper;

        public ChampionshipController(ApplicationDbContext _db, IMapper _mapper)
        {
            db = _db;
            this.mapper = _mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> ChampionshipForm()
        {
            ViewBag.Games = await db.Games.Select(x => new Game_VM { GameId = x.GameId, GameName = x.GameName }).ToListAsync();
            ViewBag.Country = await db.Countries.ToListAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChampionshipForm(Championship_VM championship)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<Championship>(championship);
                    data.Invitaion = await Help.SaveFileAsync(championship.Invitaion, FilePath.ChampPath);
                    await db.Championships.AddAsync(data);
                    await db.SaveChangesAsync();
                    List<ChampionshipGames> championship_Games = new List<ChampionshipGames>();
                    //for (int i = 0; i < championship.GameIds.Length; i++)
                    //{
                    //    championship_Games.Append(new Championship_Games { ChampId = data.ChampId, GameId = championship.GameIds[i] });
                    //}
                    foreach (var item in championship.GameIds)
                    {
                        ChampionshipGames games = new ChampionshipGames() { ChampId = data.ChampId, GameId = item };
                        championship_Games.Add(games);
                    }
                    await db.ChampionshipGames.AddRangeAsync(championship_Games);
                    int res = await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                ViewBag.Games = await db.Games.Select(x => new Game_VM { GameId = x.GameId, GameName = x.GameName }).ToListAsync();
                ViewBag.Country = await db.Countries.ToListAsync();
                return View(championship);
            }
            catch (Exception ex)
            {

                throw;
            }

        }
        public async Task<IActionResult> ChampionshipQuery()
        {
            ViewBag.Games = await db.Games.Select(x => new Game_VM { GameId = x.GameId, GameName = x.GameName }).ToListAsync();
            ViewBag.Country = await db.Countries.ToListAsync();
            return View();
        }
        public async Task<IActionResult> ChampionshipFiltr(Championship_VM championship)
        {
            try
            {
                var date = new DateTime();
                List<SqlParameter> parms = new List<SqlParameter>
            {
                 new SqlParameter { ParameterName = "@startdate",SqlDbType=System.Data.SqlDbType.DateTime, Value = championship.StartDate==date?DBNull.Value:championship.StartDate },
                 new SqlParameter { ParameterName = "@enddate", SqlDbType=System.Data.SqlDbType.DateTime,Value = championship.EndDate==date?DBNull.Value:championship.EndDate },
                 new SqlParameter { ParameterName = "@name", Value = championship.ChampName==null?DBNull.Value:championship.ChampName },
                 new SqlParameter { ParameterName = "@season", Value = championship.Season==null?DBNull.Value:championship.Season },
                 new SqlParameter { ParameterName = "@country",SqlDbType=System.Data.SqlDbType.Int, Value = championship.CountryId==-1?DBNull.Value:championship.CountryId },
                 new SqlParameter { ParameterName = "@city", Value = championship.City==null?DBNull.Value:championship.City },

            };
                if (championship.GameIds2!="[]")
                {
                    var list = new List<Champ>();
                    int[] GameIds = JsonConvert.DeserializeObject<int[]>(championship.GameIds2);
                    
                    foreach (var item in GameIds)
                    {
                        parms.Add(new SqlParameter { ParameterName = "@game", SqlDbType = System.Data.SqlDbType.Int, Value = item });
                        list.AddRange(await db.champs.FromSqlRaw("EXECUTE FilterChamp @startdate,@enddate,@name,@season,@country,@city,@game", parms.ToArray()).ToListAsync());
                        parms.Remove(parms.Last());
                    }
                    return Json(list);
                }
                
                var data = await db.champs.FromSqlRaw("EXECUTE FilterChamp @startdate,@enddate,@name,@season,@country,@city", parms.ToArray()).ToListAsync();
                return Json(data);
            }
            catch (Exception ex)
            {

                return Json(false);
            }
            
        }
        public async Task<IActionResult> ChampionshipStatus()
        {
            ViewBag.Champ = await db.Championships.Select(x => new Championship_VM { ChampName = x.ChampName, ChampId = x.ChampId }).ToListAsync();
            return View();
        }
        public async Task<IActionResult> GetChampById(int champid)
        {
            var chek =await db.ChampStatuses.Where(x => x.ChampId == champid).FirstOrDefaultAsync();
            var data = new ChampStatus_VM();
            if (chek!=null)
            {
                 data = await db.ChampStatuses.Where(x => x.ChampId == champid).Select(x => new ChampStatus_VM
                {
                    GameIds = string.Join("-", db.ChampionshipGames.Where(x => x.ChampId == champid).Select(x => x.Game.GameName).ToList()),
                    ChampName = x.Championship.ChampName,
                    StartDate = x.Championship.StartDate,
                    EndDate = x.Championship.EndDate,
                    City = x.Championship.City,
                    ChampInvChek = x.ChampInvChek,
                    AddresTheauthChek = x.AddresTheauthChek,
                    BookTicketChek = x.BookTicketChek,
                    DelegChek = x.DelegChek,
                    FinancialChek = x.FinancialChek,
                    NominationPlayerChek = x.NominationPlayerChek,
                    PayOfFeesChek = x.PayOfFeesChek,
                    PRChek = x.PRChek,
                    PromisChek = x.PromisChek,
                    RegByNamesChek = x.RegByNamesChek,
                    RegNumChek = x.RegNumChek,
                    RePortChek = x.RePortChek,
                    ResidenceChek = x.ResidenceChek,
                    ResultsChek = x.ResultsChek,
                    SportFreeTimeChek = x.SportFreeTimeChek,
                    UniformChek = x.UniformChek,
                    VisaChek = x.VisaChek,
                }).FirstOrDefaultAsync();
            }
            else
            {
                data = await db.Championships.Where(x => x.ChampId == champid).Select(x => new ChampStatus_VM
                {
                    GameIds = string.Join("-", db.ChampionshipGames.Where(x => x.ChampId == champid).Select(x => x.Game.GameName).ToList()),
                    ChampName = x.ChampName,
                    StartDate = x.StartDate,
                    EndDate = x.EndDate,
                    City = x.City,
                }).FirstOrDefaultAsync();
            }
           
            return Json(data);
        }
        public async Task<IActionResult> AddChampStatus(ChampStatus champStatus)
        {
            try
            {
                var chamstatus = await db.ChampStatuses.Where(x => x.ChampId == champStatus.ChampId).FirstOrDefaultAsync();
                if (chamstatus == null)
                {
                    await db.ChampStatuses.AddAsync(champStatus);
                    int res = await db.SaveChangesAsync();
                    if (res >0)
                    {
                        return Json(true);
                    }
                    else
                    {
                        return Json(false);
                    }
                }
                else
                {
                    chamstatus.AddresTheauthChek = champStatus.AddresTheauthChek;
                    chamstatus.BookTicketChek = champStatus.BookTicketChek;
                    chamstatus.ChampInvChek = champStatus.ChampInvChek;
                    chamstatus.DelegChek = champStatus.DelegChek;
                    chamstatus.FinancialChek = champStatus.FinancialChek;
                    chamstatus.NominationPlayerChek = champStatus.NominationPlayerChek;
                    chamstatus.PayOfFeesChek = champStatus.PayOfFeesChek;
                    chamstatus.PRChek = champStatus.PRChek;
                    chamstatus.PromisChek = champStatus.PromisChek;
                    chamstatus.RegByNamesChek = champStatus.RegByNamesChek;
                    chamstatus.RegNumChek = champStatus.RegNumChek;
                    chamstatus.RePortChek = champStatus.RePortChek;
                    chamstatus.ResidenceChek = champStatus.ResidenceChek;
                    chamstatus.ResultsChek = champStatus.ResultsChek;
                    chamstatus.SportFreeTimeChek = champStatus.SportFreeTimeChek;
                    chamstatus.UniformChek = champStatus.UniformChek;
                    chamstatus.VisaChek = champStatus.VisaChek;
                    int res = await db.SaveChangesAsync();
                    if (res > 0)
                    {
                        return Json(true);

Mo3aqin/Views/Championship/ChampionshipForm.cshtml
@model Championship_VM
@{
    ViewBag.Titel = "تسجيل بطولة";
}

<form asp-action="ChampionshipForm" asp-controller="Championship" method="post" enctype="multipart/form-data" class="">
    <div class="mx-auto text-center my-4">
        <h2 class="my-3">تسجيل بطولة جديدة</h2>
    </div>
    <div class="form-group">
        <label for="text-one">إسم البطولة</label>
        <input type="text" asp-for="ChampName" class="form-control" id="ChampName">
        <span class="text-danger" asp-validation-for="ChampName"></span>
    </div>
    <hr class="my-2">
    <div class="form-group">
        <label class="" for="check-one"> اللعبة </label>
        @foreach (var item in ViewBag.Games)
        {
            <div class="custom-control custom-checkbox">
                <input name="GameIds" class="custom-control-input" type="checkbox" value="@item.GameId" id="@item.GameId">
                <label class="custom-control-label" for="@item.GameId"> @item.GameName</label>
            </div>

        }
        <span class="text-danger" asp-validation-for="GameIds"></span>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="date-input-one">تاريخ بداية البطولة</label>
            <div class="input-group">
                <input type="text" asp-for="StartDate" class="form-control drgpicker" id="date-input-one" value="" aria-describedby="button-addon2">
                <div class="input-group-append">
                    <div class="input-group-text" id="button-addon-date"><span class="fe fe-calendar fe-16"></span></div>
                </div>
                <span class="text-danger" asp-validation-for="StartDate"></span>
            </div>
        </div>
        <div class="form-group col-md-6">
            <label for="date-input-two">تاريخ نهاية البطولة</label>
            <div class="input-group">
                <input asp-for="EndDate" type="text" class="form-control drgpicker" id="date-input-two" value="" aria-describedby="button-addon2">
                <div class="input-group-append">
                    <div class="input-group-text" id="button-addon-date"><span class="fe fe-calendar fe-16"></span></div>
                </div>
                <span class="text-danger" asp-validation-for="EndDate"></span>
            </div>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="file-one">الدعوة</label>
            <input asp-for="Invitaion" type="file" id="file-one" class="form-control-file">
            <span class="text-danger" asp-validation-for="Invitaion"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="select-one">البلد</label>
            <select asp-for="CountryId" class="form-control " id="select-one">
                <option value="-1">اختر بلد</option>
                @foreach (var item in ViewBag.Country)
                {
                    <option value="@item.CountryId">@item.CountryName</option>
                }

            </select>
            <span class="text-danger" asp-validation-for="CountryId"></span>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="text-three">المدينة</label>
            <input asp-for="City" type="text" id="text-three" class="form-control">
            <span class="text-danger" asp-validation-for="City"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="text-four">موسم</label>
            <input asp-for="Season" type="text" id="text-four" class="form-control">
            <span class="text-danger" asp-validation-for="Season"></span>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="text-five">مدة البطولة</label>
            <input asp-for="ChampDuration" type="text" id="text-five" class="form-control">
            <span class="text-danger" asp-validation-for="ChampDuration"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="text-six">عدد الإداريين</label>
            <input asp-for="EmpsNum" type="text" id="text-six" class="form-control">
            <span class="text-danger" asp-validation-for="EmpsNum"></span>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="text-seven">عدد اللاعبين</label>
            <input asp-for="PlayersNum" type="text" id="text-seven" class="form-control">
            <span class="text-danger" asp-validation-for="PlayersNum"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="text-eight">عدد المدربين</label>
            <input asp-for="CoachsNum" type="text" id="text-eight" class="form-control">
            <span class="text-danger" asp-validation-for="CoachsNum"></span>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-group">
        <label class="" for="text-nine">توصية الدكتور </label>
        <textarea asp-for="Notes" id="text-nine" name="" class="form-control" id="" cols="30" rows="5"></textarea>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <button class="btn btn-lg btn-primary col-md-5" type="submit">حفظ</button>
        <div class="form-group col-md-2"></div>
        <button class="btn btn-lg btn-primary col-md-5" type="submit">ترشيح مدرب</button>
    </div>
    <p class="mt-5 mb-3 text-muted text-center">© 2021</p>
</form>
<script>
    function add() {
        var ChampName = $('#ChampName').val();
        var 
    }
</script>

Mo3aqin/Views/Championship/ChampionshipPlayers.cshtml
@{
    ViewBag.Titel = "ترشيح الاعبين";
}

<form class="">
    <div class="mx-auto text-center my-4">
        <h2 class="my-3">ترشيح اللاعبين</h2>
    </div>
    <div class="form-row">
        <label for="select-one">اسم البطولة</label>
        <select class="form-control " id="champ">
            <option value="-1">اختر بطولة</option>
            @foreach (var item in ViewBag.Champ)
            {
                <option value="@item.ChampId">@item.ChampName</option>
            }
        </select>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            
            <label for="game">اللعبة</label>
            <input readonly disabled type="text" class="form-control" id="game">
        </div>
        <div class="form-group col-md-6">
            <label for="Comp">المنافسة</label>
            <input readonly disabled type="text" class="form-control" id="Comp">
        </div>
    </div>
    <hr class="my-2">
    <div class="form-group">
        <label class="" for="check-one">اللاعبين</label>
        <div id="data">
            
        </div>
        
    </div>
    <hr class="my-2">
    <button class="btn btn-lg btn-primary btn-block" onclick="AddChampPlayer()" type="button">حفظ</button>
    <p class="mt-5 mb-3 text-muted text-center">© 2021</p>
</form>
<script>
    $(document).ready(function () {
        $('#champ').on('change', function () {
            $.ajax({
                url: "/Championship/GetChampPlayerById?champId=" + this.value,
                type: "GET",
                dataType: "json",
                success: function (result) {
                    debugger;
                    /*$('#champname').html(result.champName);*/
                    $('#game').val(result.gameIds);
                    $('#Comp').val(result.comptions);
                    var html = "";
                    $.each(result.players, function (key, item) {
                        html += '<div class="custom-control custom-checkbox">' +
                            '<input class="custom-control-input" name="players" type = "checkbox" value = "' + item.playerId + '" id ="pl_' + item.playerId + '" >' +
                            '<label class="custom-control-label" for="pl_' + item.playerId + '">' + item.playerName + '</label></div >'
                    });
                   
                    $('#data').html(html);
                    if (result.playerschIds != null) {
                        $.each(result.playerschIds, function (key, item) {
                            debugger;
                            $("#pl_" + item).prop("checked", true)
                        });
                    }
                }
            });
        });
    })
    function AddChampPlayer() {
        var champId = $('#champ').val();
        var PlayerIds = new Array();
        $('input[name="players"]:checked').each(function () {
            PlayerIds.push($(this).val());
        });
        var formData = new FormData();
        formData.append("ChampId", champId);
        formData.append("PlayersIds", JSON.stringify(PlayerIds))
        $.ajax({
            url: "/Championship/AddChampPlayers",
            type: "POST",
            data: formData,
            dataType: 'json',
            processData: false,
            contentType: false,
            success: function (result) {

                if (result == true) {
                    swal("تم الحفظ بنجاح", "", "success");
                    $("form")[0].reset();
                    
                }
                else {
                    swal("حدث خطأ", "", "error");

                }
            }
        });
    }
</script>

Mo3aqin/Views/Championship/ChampionshipQuery.cshtml
@{
    ViewBag.Titel = "استعلام البطولات";
}

<form class="">
    <div class="mx-auto text-center my-4">
        <h2 class="my-3">إستعلام البطولات</h2>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="date-input-one">من تاريخ</label>
            <div class="input-group">
                <input dir="rtl" type="date" class="form-control " id="start" value="" aria-describedby="button-addon2">
                
            </div>
        </div>
        <div class="form-group col-md-6">
            <label for="date-input-two">إلى تاريخ</label>
            <div class="input-group">
                <input dir="rtl" type="date" class="form-control " id="end" value="" aria-describedby="button-addon2">
                
            </div>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="text-one">إسم البطولة</label>
            <input type="text" class="form-control" id="champname">
        </div>
        <div class="form-group col-md-6">
            <label for="date-input-three">الموسم</label>
            <div class="input-group">
                <input type="text" class="form-control " id="season" value="" >
            </div>
        </div>
    </div>
    <hr class="my-2">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="select-one">البلد</label>
            <select class="form-control" id="counrty">
                <option value="-1">اختر بلد</option>
                @foreach (var item in ViewBag.Country)
                {
                    <option value="@item.CountryId">@item.CountryName</option>
                }
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="select-two">المدينة</label>
            <input type="text" class="form-control " id="city" value="">
        </div>
    </div>
    <hr class="my-2">
    <div class="form-group">
        <label class="" for="check-one"> اللعبة </label>
        @foreach (var item in ViewBag.Games)
        {
            <div class="custom-control custom-checkbox">
                <input name="GameIds" class="custom-control-input" type="checkbox" value="@item.GameId" id="@item.GameId">
                <label class="custom-control-label" for="@item.GameId"> @item.GameName</label>
            </div>

        }
    </div>
    <hr class="my-2">
    <button class="btn btn-lg btn-primary btn-block" onclick="getData();" type="button">إستعلام</button>
    <hr class="my-2">
    <div class="form-row">
        <table class="table table-bordered mb-0">
            <thead>
                <tr class="bg-primary text-white">
                    <th>اسم البطولة</th>
                    <th>اللعبة</th>
                    <th>التاريخ</th>
                    <th>المكان</th>
                    <th>مدة البطولة</th>
                    <th>إجمالي الوفد</th>
                </tr>
            </thead>
            <tbody id="data">
                <tr>
                   
                </tr>
            </tbody>
        </table>
    </div>
    <p class="mt-5 mb-3 text-muted text-center">© 2021</p>
</form>
<script>
    $(document).ready(function () {
       
    })
    function getData() {
        debugger;
        var start = $("#start").val();
        var end = $("#end").val();
        var champname = $("#champname").val();
        var counrty = $("#counrty").val();
        var city = $("#city").val();
        var GameIds = new Array();
        $('input[name="GameIds"]:checked').each(function () {
            GameIds.push($(this).val());
        });
        var formData = new FormData();
        formData.append("StartDate", start)
        formData.append("EndDate", end)
        formData.append("CountryId", counrty)
        formData.append("City", city)
        formData.append("ChampName", champname)
        formData.append("GameIds2", JSON.stringify(GameIds))
        $.ajax({
            url: "/Championship/ChampionshipFiltr",
            type: "POST",
            data: formData,
            dataType: 'json',
            processData: false,
            contentType: false,
            success: function (result) {
                console.log(result);
                if (result == false) {
                    swal("حدث خطأ", "", "error");
                }
                else {
                    var html = "";
                    $.each(result, function (key, item) {
                        html += '<tr><td>' + item.champName + '</td><td>' + item.gameName + '</td><td>' + item.startDate.substring(0, 10) + '</td><td>' + item.city + '</td><td>' + item.champDuration + ' أيام</td><td>' + (item.empsNum + item.playersNum + item.coachsNum) + '</td></tr>';
                    })
                    $('#data').html(html);
                }
            }
        });
     
    }
</script>

Mo3aqin/Views/Championship/Index.cshtml
@{
    ViewBag.Titel = "البطولات";
}

<form class="">
    <div class="mx-auto text-center my-4">
        <h2 class="my-3">البطولات</h2>
    </div>
    <hr class="my-2">
    <a asp-action="ChampionshipForm" class="btn btn-lg btn-primary btn-block" >بطولة جديدة</a>
    <hr class="my-2">
    <a asp-action="ChampionshipStatus" class="btn btn-lg btn-primary btn-block" >حالة البطولات</a>
    <hr class="my-2">
    <a asp-action="ChampionshipQuery" class="btn btn-lg btn-primary btn-block" >الإستعلام</a>
    <hr class="my-2">
    <p class="mt-5 mb-3 text-muted text-center">© 2021</p>
</form>